apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260522-190259-yzlwswpxhd8c-service
spec:
  selector:
    app: enterprise-system-20260522-190259-yzlwswpxhd8c
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
